# -*- coding: utf-8 -*-
"""sign_language.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y3_yMX6EPeF1cSaldgV4YpkHA3tm5ZiS

# MNIST Sign Language
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics         import accuracy_score
from sklearn.model_selection import train_test_split

import keras
from keras.utils  import to_categorical
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout

class SignLanguage:
    def __init__(self):
        self.model = None

        self.data = {
            "train": None,
            "test" : None
        }
        self.create_model()

    def create_model(self):
        """
        Create a CNN model and save it to self.model
        """

        # TODO: Create a Sequential model
        model = Sequential()

        # 1st convolutional layer with 64 filters
        model.add(Conv2D(64, (3, 3), strides=1, input_shape=(28, 28, 1)))

        # 1st MaxPool layer for reducing dimension
        model.add(MaxPooling2D(pool_size=(2, 2)))

        # using 30% dropout for preventing overfitting
        model.add(Dropout(0.3))

        # 2nd convolutional layer with 64 filters
        model.add(Conv2D(128, (3, 3), activation='relu'))

        # 2nd MaxPool layer
        model.add(MaxPooling2D(pool_size=(2, 2)))

        # Incresing dropout for more regularization
        model.add(Dropout(0.4))

        # flattening output to 1 dimensional vector
        model.add(Flatten())

        # fully connected layer with 256 neurons
        model.add(Dense(256, activation='relu'))

        # dropout for dense layer
        model.add(Dropout(0.5))

        # using softmax activation for classification
        model.add(Dense(num_classes, activation='softmax'))


        # TODO: Compile the model with categorical_crossentropy
        model.compile('adam', loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])

        self.model = model

    def prepare_data(self, images, labels):
        """
        Use this method to normalize the dataset and split it into train/test.
        Save your data in self.data["train"] and self.data["test"] as a tuple
        of (images, labels)

        :param images numpy array of size (num_examples, 28*28)
        :param labels numpy array of size (num_examples, )
        """
        # reshaping images from (#examples, 28, 28) to (#examples, 28, 28, 1)
        images = images.reshape(-1, 28, 28, 1)

        # normalizing images to be in [0, 1]
        images = images / 255.0

        # one-hot representation
        labels = to_categorical(labels, num_classes)

        # splitting data to 80% for training set and 20% for testing set
        x_train, x_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)

        # saving data in self.data dictionary
        self.data = {
            "train": (x_train, y_train),
            "test" : (x_test, y_test)
        }

    def train(self, batch_size:int=128, epochs:int=50, verbose:int=1):
        """
        Use model.fit() to train your model. Make sure to return the history for a neat visualization.

        :param batch_size The batch size to use for training
        :param epochs     Number of epochs to use for training
        :param verbose    Whether or not to print training output
        """

        x_train, y_train = self.data["train"]
        x_test, y_test = self.data["test"]

        history = self.model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=verbose, validation_data=(x_test, y_test))

        return history

    def predict(self, data):
        """
        Use the trained model to predict labels for test data.

        :param data: numpy array of test images
        :return a numpy array of test labels. array size = (num_examples, )
        """

        # normalize the data in the same way as training data
        # self.model.predict() and np.argmax( , axis=1) might help

        data = data / 255.0

        data = data.reshape(-1, 28, 28, 1)

        # predicting probabilities for each class
        predictions = self.model.predict(data)

        # indices of maximum probabilities
        predicted_output = np.argmax(predictions, axis=1)


        return predicted_output

    def visualize_data(self, data):
        """
        Visualizing the hand gestures

        :param data: numpy array of images
        """
        if data is None: return

        nrows, ncols = 5, 5
        fig, axs = plt.subplots(nrows, ncols, figsize=(10, 10), sharex=True, sharey=True)
        plt.subplots_adjust(wspace=0, hspace=0)

        for i in range(nrows):
            for j in range(ncols):
                axs[i][j].imshow(data[0][i*ncols+j].reshape(28, 28), cmap='gray')
        plt.show()

    def visualize_accuracy(self, history):
        """
        Plots out the accuracy measures given a keras history object

        :param history: return value from model.fit()
        """
        if history is None: return

        plt.plot(history.history['accuracy'])
        plt.plot(history.history['val_accuracy'])
        plt.title("Accuracy")
        plt.xlabel('epoch')
        plt.ylabel('accuracy')
        plt.legend(['train','test'])
        plt.show()

"""# Grading Script

Do NOT modify this section
"""

if __name__=="__main__":
    train = pd.read_csv('train.csv')
    test  = pd.read_csv('test.csv')

    train_labels, test_labels = train['label'].values, test['label'].values
    train.drop('label', axis=1, inplace=True)
    test.drop('label', axis=1, inplace=True)

    num_classes = test_labels.max() + 1
    train_images, test_images = train.values, test.values

    print(train_images.shape, train_labels.shape, test_images.shape, test_labels.shape)

if __name__=="__main__":
    my_model = SignLanguage()
    my_model.prepare_data(train_images, train_labels)

if __name__=="__main__":
    my_model.visualize_data(my_model.data["train"])

if __name__=="__main__":
    history = my_model.train(epochs=30, verbose=1)
    my_model.visualize_accuracy(history)

if __name__=="__main__":
    y_pred = my_model.predict(test_images)
    accuracy = accuracy_score(test_labels, y_pred)
    print(accuracy)
